// Olympia Review Room — manifest. Paths are relative to the served Projects/ root (see serve.sh).
// Asset: dir = SM_RV folder name under 1_Execution, img = root render, glb = file inside "3D model/".
var A = {
  kotinos: {code:'SM_RV_16', dir:'SM_RV_16_KOTINOS - OLIVE WREATH “ATHENS 2004”', img:'SM_RV_16_Olive_Crown.png',  name:'Kotinos — olive wreath, Athens 2004', mb:116.7},
  medal1870: {code:'SM_RV_1', dir:'SM_RV_1_MEDAL - B SECOND ZAPPIA OLYMPIA 1870', img:'SM_RV_1_Medal_Coin.png',  name:'Medal, Zappian Olympia 1870', mb:24.5},
  medal1896: {code:'SM_RV_6', dir:'SM_RV_6_PARTICIPATION COMMEMORATIVE MEDAL “ATHENS 1896”', img:'SM_RV_6_Medal_1896.png',  name:'Medal, Athens 1896', mb:35.0},
  torch: {code:'SM_RV_12', dir:'SM_RV_12_OLYMPIC TORCH “BERLIN 1936”', img:'SM_RV_12_Torch.png',  name:'Olympic Torch, Berlin 1936', mb:15.2},
  cup: {code:'SM_RV_14', dir:'SM_RV_14_MARATHON CUP MESOLYMPIC GAMES “ATHENS 1906”', img:'SM_RV_14_Cup.png',  name:'Marathon Cup, Athens 1906', mb:50.7},
  belt: {code:'SM_RV_22', dir:'SM_RV_22_COMPETITION BELT NIKOLAOS ILIADIS “MONTREAL 1976”', img:'SM_RV_22_Belt.png',  name:'Competition Belt, Iliadis 1976', mb:32.2},
  redshoes: {code:'SM_RV_19', dir:'SM_RV_19_COMPETITION SHOES STELIOS MYGIAKIS “MOSCOW 1980”', img:'SM_RV_19_red_shoes.png',  name:'Competition Shoes, Mygiakis 1980', mb:22.1},
  shoes: {code:'SM_RV_18', dir:'SM_RV_18_COMPETITION SHOES MILTIADIS TENTOGLOU “TOKYO 2020”', img:'SM_RV_18_white_shoes_tokyo.png',  name:'Competition Shoes, Tentoglou 2020', mb:47.7},
  sword: {code:'SM_RV_13', dir:'SM_RV_13_COMPETITION SWORD DIMITRA MAGANOUDAKIS “ATHENS 2004”', img:'SM_RV_13_Blade.png',  name:'Épée, Maganoudaki 2004', mb:47.8},
  arrow: {code:'SM_RV_9', dir:'SM_RV_9_COMPETITION ARROW EVANGELIA PSARRA “LONDON 2012”', img:'SM_RV_9_Arrow.png',  name:'Competition Arrow, Psarra 2012', mb:2.0},
  wpball: {code:'SM_RV_23', dir:'SM_RV_23_COMPETITION BALL OF HELLENIC NATIONAL WATER POLO TEAM “RIO 2016”', img:'SM_RV_23_Volleyball2016.png',  name:'Water-polo Ball, Rio 2016', mb:14.8},
  club: {code:'SM_RV_8', dir:'SM_RV_8_HELLENIC NATIONAL TEAM ENSEMBLE “SYDNEY 2000” - Rhythmic Gymnastics Club', img:'SM_RV_8_Rhythmic_Gymnastics_Clubs.png',  name:'Rhythmic Gymnastics Club, 2000', mb:63.6},
  racket: {code:'SM_RV_15', dir:'SM_RV_15_COMPETITION RACKET PANAGIOTIS GIONIS “RIO 2016”', img:'SM_RV_15_ping_pong.png',  name:'Racket, Gionis 2016', mb:34.5}
};
var V='media/v/', R='media/r/';

var S='refs/';


// Families: how the sections are grouped, coloured and explained in the nav and intro.
var FAMILIES = [
  { id:'chapter', label:'Chapters', color:'#a07a1e', icon:'📖', what:'The film, built the new way — one chapter per museum unit, each scene grounded in real archival references with verified licences. This is where the work goes from now on.' },
  { id:'scene',   label:'Finished scenes', color:'#bc5a22', icon:'🎞', what:'Complete artefact scenes produced earlier: one museum object carried through a whole moment. The First Flame is the fidelity standard; the others are earlier and not yet re-verified to it.' },
  { id:'cut',     label:'Earlier trailer cuts', color:'#2e7d78', icon:'🎬', what:'The two-cut trailer assembled before the research method existed (A = the flame across time, B = sport as sound), plus the animated provenance anchors and context shots. Reference material and reusable parts — not the final film.' },
  { id:'test',    label:'Tests & experiments', color:'#6b5f8a', icon:'🧪', what:'Controlled experiments that set the rules: the character-sheet with/without-artefact test, the model bake-offs, the early pipeline tests. Results, not deliverables.' }
];

var MANIFEST = [
  { id:'u1a', family:'chapter', tag:'CHAPTER 1a', title:'The Rediscovery of Olympia', sub:'Unit 1 · the museum\'s opening movement', color:'#a07a1e',
    story:'<b>The chapter:</b> Olympia lost to time under the Alpheios\' silt, found again — Chandler 1766, the French in 1829, the German excavations of 1875–81. Every scene in this chapter is grounded in real archival images with verified licences; nothing is invented. Open a scene, watch the shots; the research behind each scene is one tab over.',
    buttons:[{label:'📜 Reference sheet', href:S+'1a-rediscovery.html', ghost:true},{label:'👤 Character sheet + style guide', href:S+'1a-character-style-sheet.html', ghost:true},{label:'🎞 Storyboard panels', href:S+'1a-storyboard/1a_storyboard_panels.jpg', ghost:true}],
    scenes:[
      { title:'The first drum — the German dig at the Temple of Zeus, 1875/76',
        story:'<b>The moment:</b> the first German season. A Doric column drum of the Temple of Zeus, buried since the earthquakes of the sixth century, coming clear of the earth under a workman\'s hands — while the German scholar who has only ever read about this temple sees it with his own eyes. <em>"Europe wanted to see the grandeur of the past with its own eyes"</em> — the museum\'s line, made literal. Three shots of one moment: wide · medium · close.',
        shots:[
      {num:1, key:'1a-whole', title:'THE WHOLE SCENE — five shots in ONE generation (Seedance 2.5 multishot, 20 s)', desc:'<b>Philipp\'s idea:</b> "just say what we want in different scenes and see what happens." <i>Pipeline:</i> 5 bound refs (2K hero frame · workman · archaeologist · plate · storyboard panels) → <b>Seedance 2.5, one 20-second generation</b>, five timestamped shots in one multishot prompt, 298 words. <b>Result:</b> the four hard cuts landed at 4.17 / 9.88 / 13.79 / 16.75 s against 4 / 10 / 14 / 17 specified; every shot correct and in order (empty dig → hero wide → lever close-up → hands on the flute → archaeologist\'s final beat); same characters across shots; scale holds. Verified by storyboard by eye. Multishot was publicly documented for 2.0 only (15 s, 3 shots). <b>Consequence:</b> a 3–5-shot scene can be one generation with consistency for free. Known drift: a dark vest on the lever labourer (shot 3) — the scoping fix applies.', asset:null, status:'final', versions:[{label:'whole scene · 20 s', src:'refs/1a-generated/'+'1a_multishot_20s.mp4'}], prompt:'scenes/'+'1a-multishot-whole-scene.md', ledger:'refs/1a-generated/'+'1a_multishot_20s.ledger.json'},
      {num:2, key:'1a-k1', title:'k1 — "The first drum" · the hero wide · v4b ✓ (k1 of record)', desc:'<b>v4b — the k1 of record.</b> <i>Pipeline:</i> Nano Banana Pro sheets + plate → composited start image (ratio 1.46) <b>upscaled to 2K</b> → Seedance 2.5 omni-reference, <b>3 bound refs</b>, the <b>75-word timestamped-format prompt</b> with every referent named. Scale holds (~1.4); the block settles in the <em>middle distance</em> with the foreground drum clean; both characters react. <b>The versions tell the story:</b> <em>v1</em> static, chest-high drum · <em>v2</em> reactions fixed, scale failed (0.40) · <em>v3</em> scale fixed by the start image, 459-word prose · <em>v4</em> new prompt format, but "it tips" bound to the wrong object · <em>v4b</em> "the block" named — correct. Same quality as v3 at one-sixth the words.', asset:null, status:'final', versions:[{label:'v4b ✓', src:'refs/1a-generated/'+'k1_v4b_genhq.mp4'},{label:'v4', src:'refs/1a-generated/'+'k1_v4_genhq.mp4'},{label:'v3', src:'refs/1a-generated/'+'k1_v3.mp4'},{label:'v2', src:'refs/1a-generated/'+'k1_v2.mp4'},{label:'v1', src:'refs/1a-generated/'+'k1.mp4'}], prompt:'scenes/'+'1a-k1-hero-prompt.md', ledger:'refs/1a-generated/'+'k1_v4b_genhq.ledger.json'},
      {num:3, key:'1a-k2', title:'k2 — "The lever" · close-up of the men moving the column (NEXT)', desc:'<b>Philipp\'s pick:</b> a close-up of the two men levering the stone, derived from k1 v1\'s moment. Composition and beat come from v1; <b>costume comes from the sheet, not from v1</b> — in v1 the two men are bare-chested, which the 1875/76 photograph contradicts and our NEVER list forbids; the wide got away with it at distance, a close-up cannot. Method: keyframe first (imagegen), then animate from the start image (videogen) — the k1 v3 rule. Open the prompt for the derivation chain, the claim ledger, the references and the exact wording.', asset:null, status:'shot', note:'awaiting two taste calls (beat: strain or give? · framing: hands-only or waist-up?)', prompt:'scenes/'+'1a-k2-closeup-prompt.md'},
      {num:4, key:'1a-k3', title:'k3 — THE DIG · close (the hands and the stone)', desc:'The workman\'s dusty hands brush earth from a fluted Doric drum; the flute emerges. No text on the stone. <em>Derived from k2.</em>', asset:null, status:'missing', note:'to derive from k2'},
        ],
        refgroups:[
      { tag:'ARCHIVAL', title:'The excavation, as it was photographed and drawn', note:'The 1829 French survey and the 1875–96 photographs: the primary record of the rediscovery. Costume, composition and scale for the scene come from here.', refs:[
        {num:5, key:'1a-ref1', title:'The German excavation in progress, 1875/76', desc:'Workmen in fustanellas among fallen column drums of the Temple of Zeus; the archaeologists in dark suits. <b>The keyframe anchor</b> — "people finding the artefacts."', src:S+'1a-sources/OlympiaGermanExcavation.jpg',
          holder:'Wikimedia Commons — category "1875/1876 excavations in Olympia"', date:'1875–76 (first German season)', creator:'Excavation documentation, Curtius / Adler / Hirschfeld campaign', source:'Photograph from the German excavation records; Commons file OlympiaGermanExcavation.jpg (500×473 px)', id:'commons: File:OlympiaGermanExcavation.jpg', licence:'public domain (19th-century photograph)', url:'https://commons.wikimedia.org/wiki/File:OlympiaGermanExcavation.jpg', found:'Commons category "Excavations in ancient Olympia" → subcategory by season (1875/1876), reached via the "Archaeological site of Olympia" category tree', verified:'downloaded + viewed 2026-08-22; licence tag to be re-checked on the file page before publication'},
        {num:6, key:'1a-ref2', title:'Plain d\'Olympie — the first excavation plan, 1829', desc:'Blouet &amp; Poirot\'s survey: the Temple of Zeus footprint (D) emerging from farmland, the Pheidias workshop. The first archaeological map of the site.', src:S+'1a-sources/Blouet-Poirot_1829_Plain-d-Olympie.jpg',
          holder:'Wikimedia Commons (original: Université Heidelberg / BnF Gallica)', date:'surveyed May 1829; published 1831–38', creator:'Guillaume-Abel Blouet & Pierre Achille Poirot', source:'Expédition scientifique de Morée, ordonnée par le Gouvernement français — Architecture, sculptures, inscriptions et vues…, Paris, Firmin Didot, vols I–VI', id:'commons: File:Plain d\'Olympie. Partie des ruines (détail).jpg · Gallica ark:/12148/bpt6k5562220x', licence:'Public Domain Mark 1.0', url:'https://commons.wikimedia.org/wiki/File:Plain_d%27Olympie._Partie_des_ruines_(d%C3%A9tail).jpg', found:'Wikipedia "Olympia, Greece" (History section image) → Commons file page; full volumes located on Gallica via search for Blouet / Expédition de Morée', verified:'downloaded + viewed 2026-08-22 (604×356 detail; full plate on Gallica at higher resolution)'},
        {num:7, key:'1a-ref3', title:'"Olympia. Panorama des ruines" — pre-1896', desc:'Three-plate albumen panorama of the freshly excavated sanctuary, the Kronos hill, the new museum on the ridge. Literally "panoramic shots of ruins being uncovered."', src:S+'1a-sources/Hallwyl_104594_Panorama-des-ruines.jpg',
          holder:'Hallwyl Museum (Hallwylska museet), Stockholm — Swedish National Historical Museums (LSH)', date:'before 1896', creator:'unidentified (commercial albumen print; caption in French)', source:'Hallwylska museet photo collection, inventory no. 104594; 5,615×1,582 px original', id:'commons: File:Fotografi från Olympia, Grekland - Hallwylska museet - 104594.tif', licence:'CC0 / CC BY-SA (LSH open release)', url:'https://commons.wikimedia.org/wiki/File:Fotografi_fr%C3%A5n_Olympia,_Grekland_-_Hallwylska_museet_-_104594.tif', found:'Commons category "Pre-1896, post-excavation photos of Olympia in the Hallwyl Museum" (under "Excavations in ancient Olympia")', verified:'downloaded + viewed 2026-08-22'},
        {num:8, key:'1a-ref4', title:'"Olympia. Fleuve Alpheios" — the river that buried it', desc:'The Alpheios bend below the site, bare hills, no buildings. The reason Olympia was lost — river silt and earthquake — in one frame. The establishing mood.', src:S+'1a-sources/Hallwyl_104595_Fleuve-Alpheios.jpg',
          holder:'Hallwyl Museum, Stockholm (LSH)', date:'before 1896', creator:'unidentified (albumen print, captioned)', source:'Hallwylska museet photo collection, inventory no. 104595; 4,140×3,481 px original', id:'commons: File:Fotografi från Olympia, Grekland - Hallwylska museet - 104595.tif', licence:'CC0 / CC BY-SA (LSH open release)', url:'https://commons.wikimedia.org/wiki/File:Fotografi_fr%C3%A5n_Olympia,_Grekland_-_Hallwylska_museet_-_104595.tif', found:'same Hallwyl category as ref 3', verified:'downloaded + viewed 2026-08-22'}
      ]},
      { tag:'LOCATION', title:'The place — the Temple of Zeus and the Kronos hill', note:'<b>Geography verified:</b> the Kronos hill lies NORTH of the Altis, the Alpheios SOUTH, the Kladeos WEST; the temple is Doric 6×13, ~20.7 m, ramp on the EAST, toppled by the earthquakes of AD 522/551 — which is why the drums lie in rows. A camera on the south side looking north is the view that reads unmistakably as Olympia. Three independent holders agree on the background; these are locked into an <em>environment plate</em> that every shot is composed on.', refs:[
        {num:9, key:'1a-loc1', title:'THE MASTER VIEW — Temple of Zeus and Kronos Hill, 1897', desc:'The temple\'s fallen drums with the wooded Kronos hill directly behind; a figure in a fustanella among the stones. The caption is printed on the card. <b>The background every shot is matched to.</b>', src:S+'1a-sources/LoC_1897_Underwood_Temple-of-Zeus-and-Kronos-Hill.jpg',
          holder:'Library of Congress, Prints & Photographs Division, Washington DC', date:'1897 (copyright date printed on the card)', creator:'Underwood & Underwood, publisher (stereograph)', source:'"Olympia, from Wall of Altis, showing Temple of Zeus and Kronos Hill, Greece" — stereograph, albumen print', id:'LC-DIG-stereo-1s26096 · LoC item 2020680922', licence:'"No known restrictions on publication" (LoC rights advisory, verbatim)', url:'https://www.loc.gov/item/2020680922/', found:'web search for Kronos hill + Temple of Zeus views → LoC catalogue; metadata and rights pulled from the LoC JSON API (the HTML pages block automated fetches)', verified:'downloaded + viewed 2026-08-22 (640×331 service file; larger tiers exist on tile.loc.gov)'},
        {num:10, key:'1a-loc2', title:'THE GEOMETRY — aerial of the Temple of Zeus, 2020', desc:'The stylobate rectangle and the drums lying in lines along the long sides, exactly where the earthquakes dropped them. Tells the generator where the rubble goes and how the platform reads from above.', src:S+'1a-sources/Commons_2020_Aerial_Temple-of-Zeus_CC-BY-2.0.jpg',
          holder:'Wikimedia Commons (imported from Flickr)', date:'22 Oct 2020', creator:'Flickr user (attribution on the Commons file page)', source:'"Aerial view of the Temple of Zeus in Olympia, Greece (51224136170)"; 5,464×3,640 px original', id:'commons: File:Aerial view of the Temple of Zeus in Olympia, Greece (51224136170).jpg', licence:'CC BY 2.0', url:'https://commons.wikimedia.org/wiki/File:Aerial_view_of_the_Temple_of_Zeus_in_Olympia,_Greece_(51224136170).jpg', found:'Commons API category listing "Temple of Zeus in Olympia" (50 members); licence read from the file\'s extmetadata', verified:'downloaded + viewed 2026-08-22'},
        {num:11, key:'1a-loc3', title:'THE TEXTURE — drums, capitals and the re-erected column, 2019', desc:'Ground level: shell-limestone blocks, drum diameter against a person, the tree-line behind. <b>Texture reference only</b> — the standing column was re-erected in 2004 and must NOT appear in an 1870s scene.', src:S+'1a-sources/Commons_2019_Temple-of-Zeus_re-erected-column_CC-BY-SA-4.0.jpg',
          holder:'Wikimedia Commons', date:'16 Jul 2019', creator:'Annatsach (Commons user)', source:'"Temple of Zeus in Olympia - 1"; 4,496×3,000 px original', id:'commons: File:Temple of Zeus in Olympia - 1.jpg', licence:'CC BY-SA 4.0', url:'https://commons.wikimedia.org/wiki/File:Temple_of_Zeus_in_Olympia_-_1.jpg', found:'same Commons category listing as loc 2; licence from extmetadata', verified:'downloaded + viewed 2026-08-22'}
      ]}
      ,{ tag:'GENERATED · STEP 0', title:'The ingredients — made from the references, gated, ready for your review', note:'<b>Philipp reviews these before any scene frame is spent.</b> Each was generated from the archival references + the written sheets (Nano Banana Pro single-reference), best-of-6, and passed both gates: the NEVER lists (confirmatory) and the exploratory pass ("is anything in frame that is not specified?"). Two candidates were rejected for captioning their own layout; one for leg-wraps. Verified by storyboard by eye against the sheets and the 1897 photograph.', refs:[
        {num:12, key:'1a-gen-workman', title:'Workman — character design sheet', desc:'Facing camera · turned 45° · side view. Knee-length <b>working</b> fustanella, plain and dust-grubby; wide-sleeved shirt on; dark sash; white headcloth; bare lower legs; rough leather shoes; period pick. No Evzone element. Same face in all three views.', src:'refs/1a-generated/'+'char_workman.png', holder:'empirica-imagegen (generated)', date:'2026-08-22', creator:'Nano Banana Pro (Google Gemini API, direct), single-reference from the 1875/76 photograph', source:'out/1a-the-rediscovery/char_workman.png · ledger char_workman.ledger.json · sha cbf45f6c04c311e2', licence:'generated — provenance via ledger', found:'Step 0 of scenes/1a-the-rediscovery.json; refs: OlympiaGermanExcavation.jpg (centre figure) + character sheet', verified:'NEVER list pass (imagegen) + viewed by storyboard 2026-08-22'},
        {num:13, key:'1a-gen-arch', title:'Archaeologist — character design sheet', desc:'Dark three-piece wool suit genuinely worn in the trench, bowler, full grey-flecked beard, wooden measuring staff. No pith helmet, no khaki. <b>Flag (below NEVER threshold):</b> jacket lapel reads lapelled in front, nearer a high collarless collar in profile — only matters if the hero needs lapel continuity across angles; re-roll available.', src:'refs/1a-generated/'+'char_archaeologist.png', holder:'empirica-imagegen (generated)', date:'2026-08-22', creator:'Nano Banana Pro (Google Gemini API, direct), single-reference from the 1875/76 photograph', source:'out/1a-the-rediscovery/char_archaeologist.png · ledger · sha 61132601e2a6d833 (alternate arch_1 rejected: captioned its layout)', licence:'generated — provenance via ledger', found:'Step 0; refs: OlympiaGermanExcavation.jpg (left group) + character sheet', verified:'NEVER list pass + viewed by storyboard; lapel inconsistency noted'},
        {num:14, key:'1a-gen-env', title:'Environment plate — the dig at the Temple of Zeus, 1870s (empty)', desc:'Camera south looking north: the rounded, wooded <b>Kronos hill</b> across the upper third, exactly as in the 1897 stereograph; Doric drums in <b>two long lines</b> flanking the trench — the temple\'s two long sides; a capital on a drum; pitted shell-limestone; raw trench walls with tool marks; spoil heaps; bare dirt. No standing column, no 2004 column, no text, no modern anything. Alternate env_2 (denser drum field) in cand/.', src:'refs/1a-generated/'+'env_temple-of-zeus_1870s.png', holder:'empirica-imagegen (generated)', date:'2026-08-22', creator:'Nano Banana Pro (Google Gemini API, direct), refs: LoC 1897 (cropped to one clean frame), Commons 2020 aerial, Hallwyl panorama', source:'out/1a-the-rediscovery/env_temple-of-zeus_1870s.png · ledger · sha 370c46b9060ff532', licence:'generated — provenance via ledger', found:'Step 0b; the LoC stereograph was pre-flighted and cropped (it carries mount + captions) — now a standing rule', verified:'location NEVER list pass; midground pale form checked at 3x = a block, not an upright; viewed by storyboard against the LoC 1897 + aerial'},
        {num:15, key:'1a-gen-k1v3start', title:'k1 v3 START IMAGE — the scale fixed at the still layer (ratio 1.46)', desc:'The workman at the foot of a drum that <b>towers over him</b> — measured drum 474 px / man 325 px = <b>1.46</b> (gate &gt; 1.0; v2 clips were 0.39–0.40). All three still candidates cleared, which localises the failure: the object-shrinks-to-body mode bites at the <em>clip</em> layer, not the still. v3 animates FROM this frame; videogen re-measures the ratio at start / mid / end of the clip. Note: a dark vest over the shirt — period-correct per the 1875/76 photo, not on the approved sheet (sheet drift, noted).', src:'refs/1a-generated/'+'k1_v3_start.png', holder:'empirica-imagegen (generated)', date:'2026-08-22', creator:'Nano Banana Pro (Google Gemini API, direct) · v1 plate + workman/archaeologist sheets + 1875/76 photo', source:'out/1a-the-rediscovery/k1_v3_start.png · sha 5b4ed94794d0f2a6 · ledger with measured bounds (drum 232–706, man 398–723)', licence:'generated — provenance via ledger', found:'k1 v3 brief: fix the scale one layer earlier (start_image) after v2 proved it prompt-resistant', verified:'viewed by storyboard; ratio auditable from the ledger bounds'}
      ]}
    ],
      }
    ]},
  { id:'ab-kling', family:'test', tag:'A/B · KLING PROMPT', title:'Does Kling need the 261-word block? No.', sub:'the kotinos, same certified still, long vs short motion prompt · 2026-08-22', color:'#6b5f8a',
    story:'<b>The question:</b> Kling is documented to want a <em>brief</em> motion prompt because the start frame drives image-to-video — but every artefact shot we made sent ~220–260 words (continuity block + invariants). <b>The test:</b> the Crowning k1 (the one kotinos shot with a <em>certified</em> still), Kling 3.0, identical everything, prompt A = 261 words, prompt B = 65 words. <b>Result: no measurable difference.</b> Both hold the dried golden-brown wreath, the open ring, the cloth binding; no green, no invented closure. Whole-frame hue drift from the certified still: A +23.2, B +27.7 — a 4.5 gap on a 0–360 scale is noise (n = 1 per arm). <b>Conclusion:</b> the long block is redundant for Kling — the keyframe carries fidelity. Short prompts from now on; a 3× repeat would harden it before the emitter changes.',
    shots:[
      {num:16, key:'ab-long', title:'A — 261-word prompt (the old block)', desc:'Continuity paragraph + invariants + no-text line, as every artefact shot sent until today. <i>Pipeline:</i> certified still → Kling 3.0 (start frame) · 5 s.', asset:'SM_RV_16', status:'test', versions:[{label:'A · 261 words', src:'refs/_ab-kling/'+'k1_AB_long.mp4'}], prompt:'refs/_ab-kling/'+'prompt_long_261w.txt', ledger:'refs/_ab-kling/'+'k1_AB.ledger.json'},
      {num:17, key:'ab-short', title:'B — 65-word prompt (brief: frames drive it)', desc:'One camera move, the one action, a hold line naming the three invariants. Deliberately without the no-text line so a win stays attributable. <i>Pipeline:</i> certified still → Kling 3.0 (start frame) · 5 s.', asset:'SM_RV_16', status:'test', versions:[{label:'B · 65 words', src:'refs/_ab-kling/'+'k1_AB_short.mp4'}], prompt:'refs/_ab-kling/'+'prompt_short_65w.txt', ledger:'refs/_ab-kling/'+'k1_AB.ledger.json'}
    ]},
  { id:'test-sheets', family:'test', tag:'TEST · SHEETS', title:'Character sheets — with and without the museum artefact', sub:'the product question, answered at the character level · 2026-08-22', color:'#6b5f8a',
    story:'<b>The experiment (Philipp\'s idea):</b> the same victor, same pose, same prompt, same model — the <em>only</em> difference is whether the museum\'s kotinos (SM_RV_16) was injected as a reference. <b>Result: WITH 5/6 invariants, WITHOUT 1/6.</b> Colour instrumented, not eyeballed: hue agreement with the real kotinos <b>0.978</b> for all three WITH candidates vs 0.49–0.62 WITHOUT. The reference is doing it, not luck. <b>The finding nobody asked for:</b> a detail <em>callout</em> is a fidelity mechanism, not a presentation choice — it puts the artefact in the large, face-on regime where a reference survives (the worn-in-scene wreath in The Crowning scored ~0.35 and lost exactly the details that survived here). So for any worn artefact: generate the sheet with its callout first, then let the scene inherit from the sheet — <b>with one carve-out, learned an hour later in sub-test C: not for text.</b> The callout rescues form; it makes inscriptions legible and wrong. Inscribed surfaces stay turned away or cropped, even in the callout.',
    buttons:[{label:'📄 Test spec', href:'scenes/_test-character-sheets-with-artefacts.json', ghost:true}],
    refgroups:[
      { tag:'B · THE PRODUCT QUESTION', title:'Victor + kotinos — WITHOUT vs WITH the museum reference', note:'Score per registry invariant. <b>WITHOUT:</b> golden-brown ✗ · lanceolate ✓* · dense ✗ · wire ties ✗ · cloth join ✗ · open ring ✗ = 1/6 (*olive leaves are lanceolate by nature). <b>WITH:</b> ✓ ✓ ✓ ✗ ✓ ✓ = 5/6 — only the thin wire ties missed, in both arms. Same wreath across all four views + callouts in both arms: the failure is stable, not noisy — the worse kind.', refs:[
        {num:18, key:'t-without', title:'WITHOUT the reference — the cliché', desc:'A fresh <b>green</b> olive wreath, sparse, a <b>closed</b> ring, no ties, no binding. A stock "Greek victor." This is what the model assumes when nothing tells it otherwise.', src:'refs/_test-character-sheets/'+'victor_kotinos_WITHOUT.png', holder:'empirica-imagegen (generated)', date:'2026-08-22', creator:'Nano Banana Pro (Google Gemini API, direct) · victor identity ref only', source:'out/_test-character-sheets/victor_kotinos_WITHOUT.png · ledger · hue 29–35, agreement 0.489–0.622', licence:'generated — provenance via ledger', found:'sub-test B, arm WITHOUT', verified:'viewed by storyboard: green, sparse, closed, no ties'},
        {num:19, key:'t-with', title:'WITH the reference — the actual Athens 2004 kotinos', desc:'Dried <b>golden-brown</b>, densely packed narrow leaves, the pale cloth binding at the join, the <b>open</b> ring where the ends overlap — and it holds in all four views (the binding is visible at the back of the head). The only miss: the thin wire ties.', src:'refs/_test-character-sheets/'+'victor_kotinos_WITH.png', holder:'empirica-imagegen (generated)', date:'2026-08-22', creator:'Nano Banana Pro (Google Gemini API, direct) · victor identity ref + SM_RV_16 render + registry invariants', source:'out/_test-character-sheets/victor_kotinos_WITH.png · ledger · hue 13.0 vs reference 12.0, agreement 0.978 (all 3 candidates)', licence:'generated — provenance via ledger', found:'sub-test B, arm WITH', verified:'viewed by storyboard against the SM_RV_16 render: same object'},
        {num:20, key:'t-real', title:'The real object — SM_RV_16, Olympic Museum render', desc:'The kotinos awarded to Ilias Iliadis, Athens 2004 (judo gold, aged 17). Dried wild olive, wire-tied stems, cloth-wrapped join, open ring. <b>The thing both arms were trying to be.</b>', src:'media/r/Unit 1/Pilot 2/Olympic Museum/1_Execution/SM_RV_16_KOTINOS - OLIVE WREATH “ATHENS 2004”/SM_RV_16_Olive_Crown.png', holder:'Olympic Museum of Thessaloniki · REEVALUATE Pilot 2 digitisation (3DR)', date:'object 2004 · digitised 2026', creator:'museum digitisation', source:'1_Execution/SM_RV_16 … /SM_RV_16_Olive_Crown.png (+ .glb 116.7 MB)', licence:'museum asset — project licence (rights line to be collected)', found:'assets/registry.json SM_RV_16', verified:'registry identity + verification record'}
      ]},
      { tag:'A · PRODUCTION FORMAT', title:'Four views + callouts — the 1a characters upgraded', note:'Four-view turnaround incl. a genuine rear view, plus a callout strip of the held and worn items (the format Philipp showed). <b>Workman: PASS.</b> <b>Archaeologist: the callout exposed an inconsistency</b> — lapels over a waistcoat facing camera vs a collarless mandarin closure in profile and in the jacket callout. A callout is a <em>diagnostic</em> for internal inconsistency, not a remedy. Settled from the costume record: the 1870s everyday coat was the high-buttoned <b>sack coat with narrow lapels</b>, waistcoat hidden behind (Victorian Web; Historical Emporium) — re-roll with that as an invariant.', refs:[
        {num:21, key:'t-workman', title:'Workman — production sheet (PASS)', desc:'Facing camera / 45° / side / from behind, plus callouts: pick, headcloth knot, sash, shoe. Same man, same objects, no text, every 1a NEVER holds.', src:'refs/_test-character-sheets/'+'workman_prod.png', holder:'empirica-imagegen (generated)', date:'2026-08-22', creator:'Nano Banana Pro · @image = approved 3-view sheet', source:'out/_test-character-sheets/workman_prod.png · ledger', licence:'generated — provenance via ledger', found:'sub-test A', verified:'callout items match the views; no text'},
        {num:22, key:'t-arch', title:'Archaeologist — production sheet (FAILS callout consistency)', desc:'Bowler, staff, boot callouts fine — but the <b>jacket callout shows a collarless mandarin closure</b> while the facing-camera view has lapels over a waistcoat. Not the same garment. <b>Ruling:</b> lapelled high-buttoned sack coat is the correct 1870s garment → re-roll.', src:'refs/_test-character-sheets/'+'archaeologist_prod.png', holder:'empirica-imagegen (generated)', date:'2026-08-22', creator:'Nano Banana Pro · @image = approved 3-view sheet', source:'out/_test-character-sheets/archaeologist_prod.png · ledger', licence:'generated — provenance via ledger', found:'sub-test A', verified:'inconsistency confirmed by storyboard by eye; costume ruling from the record'}
      ]}
      ,{ tag:'C · INSCRIPTIONS', title:'Tentoglou\'s shoes — does the callout rescue TEXT? No: it rescues LEGIBILITY, not ACCURACY', note:'<b>The refutation.</b> The object held everywhere (silhouette, stripes, spike plate, wear, same shoe in all views). The inscriptions came out crisp — and <b>wrong</b>: the gold-winning distance <b>8.41 rendered as 8.71</b> (a fabricated sporting claim about a living athlete, in his own handwriting); one panel reads <b>TOKIO on one shoe and TOKITO on the other</b>; the Greek name garbled. Legible-and-wrong is worse than illegible — it reads as authoritative (the ALS DANNK mechanism). <b>New, unguarded hazard:</b> the Greek name appeared although the prompt withheld it — the <em>reference image</em> supplied text the prompt never asked for, the exact inverse of the torch. <b>Standing rule, corrected:</b> sheet-first for form / material / structure (proven) — and every inscribed surface TURNED AWAY or CROPPED, even inside the callout; pre-crop reference images; inscriptions ride the ledger; certify text only by character-level diff.', refs:[
                        {num:23, key:'t-shoes-real', title:'The real object — SM_RV_18, Olympic Museum render', desc:'Tentoglou\'s Tokyo 2020 long-jump shoes, gold at <b>8.41 m</b>. The athlete\'s own ink: 8.41, TOKIO (not TOKYO — the object wins), and his name in Greek. <b>Every mark here is what the generated callouts got wrong.</b>', src:'media/r/Unit 1/Pilot 2/Olympic Museum/1_Execution/SM_RV_18_COMPETITION SHOES MILTIADIS TENTOGLOU “TOKYO 2020”/SM_RV_18_white_shoes_tokyo.png', holder:'Olympic Museum of Thessaloniki · REEVALUATE Pilot 2 digitisation (3DR)', date:'object 2021 · digitised 2026', creator:'museum digitisation', source:'1_Execution/SM_RV_18 … /SM_RV_18_white_shoes_tokyo.png (+ .glb 47.7 MB)', licence:'museum asset — project licence (rights line to be collected)', found:'assets/registry.json SM_RV_18', verified:'registry + verification record (TOKIO per-glyph verified on the hero still s1)'},
        {num:24, key:'t-arch-v2', title:'Archaeologist — production sheet v2 (PASS)', desc:'The costume ruling applied as an invariant: high-buttoned <b>sack coat with narrow lapels</b>, sliver of waistcoat and white collar — the same coat across all four views and the jacket callout. Lapel visibility varies with angle (physics, not a garment change). v1\'s inconsistency resolved.', src:'refs/_test-character-sheets/'+'archaeologist_prod_v2.png', holder:'empirica-imagegen (generated)', date:'2026-08-22', creator:'Nano Banana Pro · @image = approved sheet + sack-coat invariant', source:'out/_test-character-sheets/archaeologist_prod_v2.png · ledger · sha 3f4921419247', licence:'generated — provenance via ledger', found:'sub-test A re-roll after the costume ruling (Victorian Web / Historical Emporium)', verified:'viewed by storyboard: same coat in all five panels'}
      ]}
    ],
    shots:[]},
  { id:'trailerA', family:'cut', tag:'TRAILER A', title:'The Flame Never Went Out', sub:'Units 1–3 + 5 · the flame across time', color:'#bc5a22',
    story:'<b>The story:</b> the only prize (wreath) → the revival (1870 medal) → an idea reborn (1896 medal) → the flame is carried (torch) → the world came to Athens (cup) → the world runs as one (torch reaches today\'s crowd).',
    shots:[
      {num:25, key:'a1', title:'The Only Prize', desc:'The judge lowers the olive wreath onto the athlete\'s head.', asset:A.kotinos, status:'check', versions:[{label:'a1', src:V+'trailer-A/a1.mp4'}]},
      {num:26, key:'a2', title:'The Revival', desc:'The 1870 medal pressed hand to hand.', asset:A.medal1870, status:'check', versions:[{label:'a2', src:V+'trailer-A/a2.mp4'}]},
      {num:27, key:'a3', title:'An Idea Reborn', desc:'The 1896 medal turned over in the hands.', asset:A.medal1896, status:'check', versions:[{label:'a3', src:V+'trailer-A/a3.mp4'}]},
      {num:28, key:'a4', title:'The Flame Is Carried', desc:'Relay runner, torch high. <b>Engraving mismatch — adopt the First Flame treatment.</b>', asset:A.torch, status:'flag', flag:'inscription', versions:[{label:'a4', src:V+'trailer-A/a4.mp4'}]},
      {num:29, key:'a5', title:'The World Came to Athens', desc:'Hands lift the 1906 cup overhead. Two takes — the shipped one and a rejected Kling take.', asset:A.cup, status:'check', versions:[{label:'a5 (shipped)', src:V+'trailer-A/a5.mp4'},{label:'a5 kling (rejected)', src:V+'trailer-A/a5.kling-rejected.mp4'}]},
      {num:30, key:'a6', title:'The World Runs as One', desc:'Present-day fun-run; the lit torch reaches the crowd.', asset:A.torch, status:'flag', flag:'inscription', versions:[{label:'a6', src:V+'trailer-A/a6.mp4'}]},
      {num:31, key:'A-full', title:'TRAILER A — assembled', desc:'The full cut, current version.', asset:null, status:'check', versions:[{label:'current', src:V+'trailer-A/TRAILER_A.mp4'},{label:'v2 (reevaluate)', src:R+'olympia-trailer-v2/TRAILER_A.mp4'},{label:'CUT_A (earlier)', src:R+'olympia-trailer/CUT_A.mp4'}]}
    ]},
  { id:'trailerB', family:'cut', tag:'TRAILER B', title:'Every Sport Has a Sound', sub:'Unit 4 · equipment as rhythm', color:'#5b7a34',
    story:'<b>The story:</b> every piece of equipment makes its own sound — belt, shoes, board, blades, arrow, ball, club, racket — and together they make music.',
    shots:[
      {num:32, key:'b1', title:'The Belt', desc:'Hands pull the belt tight, set the buckle.', asset:A.belt, status:'check', versions:[{label:'b1', src:V+'trailer-B/b1.mp4'}]},
      {num:33, key:'b2', title:'The Shoes', desc:'A wrestler drives off one red boot.', asset:A.redshoes, status:'check', versions:[{label:'b2', src:V+'trailer-B/b2.mp4'}]},
      {num:34, key:'b3', title:'The Board', desc:'The long-jump shoe hits the board at 8.41. Needs its motion clip (still s1 exists).', asset:A.shoes, status:'missing', note:'no clip yet'},
      {num:35, key:'b4', title:'The Blades', desc:'Two fencers engaged; the épée lunge.', asset:A.sword, status:'check', versions:[{label:'b4', src:V+'trailer-B/b4.mp4'}]},
      {num:36, key:'b5', title:'The Arrow', desc:'Full draw, arrow past the jaw — then gone.', asset:A.arrow, status:'check', versions:[{label:'b5', src:V+'trailer-B/b5.mp4'}]},
      {num:37, key:'b6', title:'The Ball', desc:'A water-polo player rises, ball palmed.', asset:A.wpball, status:'check', versions:[{label:'v2 ✓ face composed out', src:'refs/trailer-B-generated/'+'b7_v2.png'},{label:'b6', src:V+'trailer-B/b6.mp4'}]},
      {num:38, key:'b7', title:'The Club', desc:'A gymnast\'s hand closes below the falling club.', asset:A.club, status:'check', versions:[{label:'b7', src:V+'trailer-B/b7.mp4'}]},
      {num:39, key:'b8', title:'The Racket', desc:'A table-tennis racket meets the ball in topspin.', asset:A.racket, status:'check', versions:[{label:'b8', src:V+'trailer-B/b8.mp4'}]},
      {num:40, key:'B-full', title:'TRAILER B — assembled', desc:'The full cut.', asset:null, status:'check', versions:[{label:'current', src:V+'trailer-B/TRAILER_B.mp4'},{label:'v2 (reevaluate)', src:R+'olympia-trailer-v2/TRAILER_B.mp4'}]}
    ]},
  { id:'anchors', family:'cut', tag:'ANCHORS', title:'The six provenance anchors — animated', sub:'each hero still brought to gentle motion', color:'#a07a1e',
    story:'<b>What these are:</b> the verified hero stills, animated at rest. These carry the historical claim — where per-glyph verification happens — and the beats compose around them.',
    shots:[
      {num:41, key:'s6', title:'Kotinos', desc:'The olive wreath at rest.', asset:A.kotinos, status:'check', versions:[{label:'s6', src:V+'trailer-anchors/s6.mp4'}]},
      {num:42, key:'s3', title:'1870 medal (reverse)', desc:'The struck olive wreath that rhymes to the kotinos.', asset:A.medal1870, status:'check', versions:[{label:'s3', src:V+'trailer-anchors/s3.mp4'}]},
      {num:43, key:'s2', title:'Berlin 1936 torch', desc:'The torch at rest. Its still had the ALS DANNK defect — superseded by the First Flame keyframe.', asset:A.torch, status:'flag', flag:'inscription', versions:[{label:'s2', src:V+'trailer-anchors/s2.mp4'}]},
      {num:44, key:'s4', title:'1906 cup', desc:'The kantharos form.', asset:A.cup, status:'check', versions:[{label:'s4', src:V+'trailer-anchors/s4.mp4'}]},
      {num:45, key:'s5', title:'Épée', desc:'Bell guard, tempered blade.', asset:A.sword, status:'check', versions:[{label:'s5', src:V+'trailer-anchors/s5.mp4'}]},
      {num:46, key:'s1b', title:'Tentoglou shoes (8.41)', desc:'The verified 8.41 mark.', asset:A.shoes, status:'check', versions:[{label:'s1b', src:V+'trailer-anchors/s1b.mp4'}]}
    ]},
  { id:'firstflame', family:'scene', tag:'FIRST FLAME', title:'The First Flame', sub:'Unit 2 · the QC\'d-final scene + certificate', color:'#bc5a22',
    story:'<b>The story:</b> the torch (object, form-forward) → the parabolic mirror catches the first modern flame at Olympia, 1936 → the first runner takes it → the country it crossed. The provenance shot is a deterministic pull-back (cannot fabricate).',
    shots:[
      {num:47, key:'ff-master', title:'The First Flame — master (~20s)', desc:'The finished scene.', asset:A.torch, status:'final', versions:[{label:'master', src:V+'the-first-flame/the-first-flame.mp4'}]},
      {num:48, key:'ff-k1', title:'k1 — The Torch (provenance)', desc:'Deterministic pull-back is what shipped; the generative version is a control only.', asset:A.torch, status:'final', versions:[{label:'deterministic (shipped)', src:V+'the-first-flame/k1_det.mp4'},{label:'generative (control)', src:V+'the-first-flame/k1.mp4'}]},
      {num:49, key:'ff-k2', title:'k2 — The Lighting', desc:'The mirror gathers the sun; the flame catches.', asset:null, status:'final', versions:[{label:'k2', src:V+'the-first-flame/k2.mp4'}]},
      {num:50, key:'ff-k3', title:'k3 — The First Runner', desc:'The runner lifts the lit torch, flame streaming.', asset:null, status:'final', versions:[{label:'k3', src:V+'the-first-flame/k3.mp4'}]},
      {num:51, key:'ff-k4', title:'k4 — Olympia to Berlin', desc:'Aerial drift; no labels. Flame reads as a pillar — aesthetic note.', asset:null, status:'final', versions:[{label:'k4', src:V+'the-first-flame/k4.mp4'}]}
    ]},
  { id:'crowning', family:'scene', tag:'CROWNING', title:'The Crowning', sub:'Unit 1 · the taking of the wreath · multiple versions', color:'#a07a1e',
    story:'<b>The story:</b> the judge crowns the victor with the kotinos; the tear; the light; the crowd; the games go on. The first full scene we drove — the kotinos carried through every shot.',
    shots:[
      {num:52, key:'cr-master', title:'The Crowning — masters', desc:'Three assembled versions: the 20s 1080p sample, v2 full, and v1.', asset:A.kotinos, status:'check', versions:[{label:'20s 1080p (D4.11 sample)', src:R+'Olympia-D4.11-samples/Olympia_THE-CROWNING_20s_1080p.mp4'},{label:'v2 full', src:V+'the-crowning-v2/SCENE_the-crowning_v2_full.mp4'},{label:'v1', src:V+'the-crowning/SCENE_the-crowning_v2.mp4'},{label:'early test', src:R+'tests/scene_crowning/SCENE_the-crowning.mp4'}]},
      {num:53, key:'cr-k1', title:'k1 — The Crowning', desc:'The wreath lowered onto the head.', asset:A.kotinos, status:'check', versions:[{label:'v2', src:V+'the-crowning-v2/k1.mp4'},{label:'v1', src:V+'the-crowning/k1.mp4'}]},
      {num:54, key:'cr-k2', title:'k2 — The Tear', desc:'Close on the victor; the judge\'s red sleeve in foreground.', asset:A.kotinos, status:'check', versions:[{label:'v2', src:V+'the-crowning-v2/k2.mp4'},{label:'v1', src:V+'the-crowning/k2.mp4'}]},
      {num:55, key:'cr-k3', title:'k3 — The Light', desc:'Face raised to the sky, wreath still on.', asset:A.kotinos, status:'check', versions:[{label:'v2', src:V+'the-crowning-v2/k3.mp4'},{label:'v1', src:V+'the-crowning/k3.mp4'}]},
      {num:56, key:'cr-k4', title:'k4 — The Crowd', desc:'He turns to the roaring crowd.', asset:A.kotinos, status:'check', versions:[{label:'v2', src:V+'the-crowning-v2/k4.mp4'},{label:'v1', src:V+'the-crowning/k4.mp4'}]},
      {num:57, key:'cr-k5', title:'k5 — The Games Go On', desc:'Aerial over the sanctuary (v2 restage).', asset:null, status:'check', versions:[{label:'v2', src:V+'the-crowning-v2/k5.mp4'}]}
    ]},
  { id:'cutting', family:'scene', tag:'WREATH CUTTING', title:'The Cutting of the Wreath', sub:'Unit 1 · the kotinos cut from the sacred olive · model bake-off', color:'#a07a1e',
    story:'<b>The story:</b> branches cut from the sacred olive by a boy with both parents living, using golden shears (Pausanias). We ran three video models head-to-head on the physics of the cut.',
    shots:[
      {num:58, key:'cut-master', title:'Cutting of the Wreath — 16s (D4.11 bonus)', desc:'The assembled scene.', asset:A.kotinos, status:'check', versions:[{label:'16s bonus', src:R+'Olympia-D4.11-samples/Olympia_D4.11_BONUS_scene_cutting-of-the-wreath_16s.mp4'},{label:'scene assembly', src:R+'tests/scene_kotinos_cutting/SCENE_kotinos_cutting.mp4'},{label:'Route B multishot (Kling3)', src:R+'tests/scene_kotinos_cutting/ROUTE-B_kling3_multishot.mp4'}]},
      {num:59, key:'cut-bake', title:'Physics bake-off — 3 models', desc:'Same cut, three generators. Which holds the shears + branch physics?', asset:A.kotinos, status:'test', versions:[{label:'Kling 3', src:R+'tests/scene_kotinos_cutting/BAKEOFF_kling3_physics.mp4'},{label:'Seedance 2', src:R+'tests/scene_kotinos_cutting/BAKEOFF_seedance2_physics.mp4'},{label:'Veo 3.1', src:R+'tests/scene_kotinos_cutting/BAKEOFF_veo31_physics.mp4'}]},
      {num:60, key:'cut-shots', title:'Individual shots 1–4', desc:'The four shots of the cutting scene.', asset:A.kotinos, status:'check', versions:[{label:'shot 1', src:R+'tests/scene_kotinos_cutting/shot1.mp4'},{label:'shot 2', src:R+'tests/scene_kotinos_cutting/shot2.mp4'},{label:'shot 3', src:R+'tests/scene_kotinos_cutting/shot3.mp4'},{label:'shot 4', src:R+'tests/scene_kotinos_cutting/shot4.mp4'}]},
      {num:61, key:'cut-c', title:'Candidates c1–c4', desc:'Alternate candidate takes.', asset:A.kotinos, status:'test', versions:[{label:'c1', src:R+'tests/scene_kotinos_cutting/c1.mp4'},{label:'c2', src:R+'tests/scene_kotinos_cutting/c2.mp4'},{label:'c3', src:R+'tests/scene_kotinos_cutting/c3.mp4'},{label:'c4', src:R+'tests/scene_kotinos_cutting/c4.mp4'}]}
    ]},
  { id:'club', family:'scene', tag:'CLUB THAT FELL', title:'The Club That Fell', sub:'Unit 4 · the rhythmic-gymnastics club drop · first end-to-end scene', color:'#5b7a34',
    story:'<b>The story:</b> the gymnast\'s club falls and is caught — the first scene driven end-to-end through the chain (5 shots). The crux was whether a physical fall renders in video.',
    shots:[
      {num:62, key:'club-master', title:'The Club That Fell — master', desc:'The assembled 5-shot scene.', asset:A.club, status:'check', versions:[{label:'master', src:V+'the-club-that-fell/SCENE_the-club-that-fell.mp4'}]},
      {num:63, key:'club-shots', title:'Shots k1–k5', desc:'The five shots.', asset:A.club, status:'check', versions:[{label:'k1', src:V+'the-club-that-fell/k1.mp4'},{label:'k2', src:V+'the-club-that-fell/k2.mp4'},{label:'k3 (the fall)', src:V+'the-club-that-fell/k3.mp4'},{label:'k4', src:V+'the-club-that-fell/k4.mp4'},{label:'k5', src:V+'the-club-that-fell/k5.mp4'}]}
    ]},
  { id:'beat1', family:'test', tag:'BEAT 1 TESTS', title:'Beat 1 explorations — kotinos & temple', sub:'early de-risk tests · Veo 3.1 · the first pipeline proof', color:'#6b5f8a',
    story:'<b>What these were:</b> the very first tests — can a static digitised object become cinematic footage? Kotinos in the temple, push-ins, a lift, a kerykeion.',
    shots:[
      {num:64, key:'t-kot', title:'Kotinos — temple push-in / lift', desc:'SAMPLE-B push-in and SAMPLE-C lift, plus the Veo push-in.', asset:A.kotinos, status:'test', versions:[{label:'SAMPLE-B push-in', src:R+'tests/SAMPLE-B_kotinos_temple_pushin.mp4'},{label:'SAMPLE-C lift', src:R+'tests/SAMPLE-C_kotinos_lift.mp4'},{label:'Veo 3.1 push-in', src:R+'tests/beat1_kotinos_pushin_veo31.mp4'},{label:'D4.11 4s clip', src:R+'Olympia-D4.11-samples/Olympia_D4.11_SAMPLE-B_clip_kotinos_4s.mp4'}]},
      {num:65, key:'t-ker', title:'Kerykeion push-in (Veo 3.1)', desc:'An early non-museum test object.', asset:null, status:'test', versions:[{label:'kerykeion', src:R+'tests/beat1_kerykeion_pushin_veo31.mp4'}]},
      {num:66, key:'t-torch', title:'Torch motion test', desc:'Does motion garble the engraving? Pull-back vs push-in vs deterministic — the test that unblocked the torch.', asset:A.torch, status:'test', versions:[{label:'Kling pull-back', src:V+'torch-motion-test/kling_pullback.mp4'},{label:'Kling push-in', src:V+'torch-motion-test/kling_pushin.mp4'},{label:'deterministic', src:V+'torch-motion-test/det_pullback.mp4'}]}
    ]},
  { id:'context', family:'cut', tag:'CONTEXT', title:'Establishing shots', sub:'videogen-direct · ruins, stadium, parade, crowds, maps · no artefact claim', color:'#6d7261',
    story:'<b>Note:</b> there is no dedicated "people finding the artefacts / excavation" scene yet — that theme (Unit 1\'s rediscovery of Olympia) exists only as context footage. Worth deciding if it deserves its own scene.',
    shots:[
      {num:67, key:'t1', title:'Context 1', asset:null, status:'check', versions:[{label:'t1', src:V+'trailer-context/t1_ctx.mp4'}]},
      {num:68, key:'t2', title:'Context 2', asset:null, status:'check', versions:[{label:'t2', src:V+'trailer-context/t2_ctx.mp4'}]},
      {num:69, key:'t3', title:'Context 3', asset:null, status:'check', versions:[{label:'t3', src:V+'trailer-context/t3_ctx.mp4'}]},
      {num:70, key:'t4', title:'Context 4', asset:null, status:'check', versions:[{label:'t4', src:V+'trailer-context/t4_ctx.mp4'}]},
      {num:71, key:'t5', title:'Context 5', asset:null, status:'check', versions:[{label:'t5', src:V+'trailer-context/t5_ctx.mp4'}]}
    ]}
];
